export const STRINGS = {
  NOT_SPECIFIED: 'לא צוין',
  FINANCIAL_SAVVY: 'חסכוני',
  HOME: 'תמונת מצב',
  CATEGORIES: 'קטגוריות',
  RECEIPS: 'קבלות',
  SETTINGS: 'הגדרות',
  CONTINUE_BUTTON_TEXT: 'המשך',
  ADD_CATEGORY: 'הוספת קטגוריה',
  ADD_NEW_CATEGORY: 'הוספת קטגוריה חדשה',
  EXPENSE_SUCCEDED: 'ההוצאה נוספה בהצלחה!',
  EXPENSE_IN: 'הוצאה של',
  LAST_EXPENSES: 'הוצאות אחרונות',
  TO_ALL_EXPENSES: `לכל ההוצאות >>`,
  NO_EXPENSES_YET: 'אין עדיין הוצאות',
  ERROE_IN_SERVER: 'תקלה בשרת כרגע, אנא נסו במועד מאוחר יותר',
  LOADING_OR_NOT_FOUND: 'טוען/לא נמצא',
  LOADING_CATEGORY: 'טוען קטגוריה...',
  ALL_EXPENSES: 'כל ההוצאות',
  EDIT_CATEGORY: 'עריכת קטגוריה',
  CATEGORY_NAME: 'שם קטגוריה',
  MAX_AMOUNT: 'תקציב חודשי',
  MAX_AMOUNT_REQUIRED_ERROR: 'תקציב חייב להיות מספר תקין וחיובי',
  MAX_AMOUNT_REQUIRED_GREATER_THAN_ZERO: 'תקציב חייב להיות גדול מאפס',
  CATEGORY_NAME_REQUIRED_ERROR: 'שם קטגוריה חובה',
  CATEGORY_CREATE_SCHEMA_INCORRECT_VALUES: 'שדות לא תקינים, בדקו את הקלט בבקשה',
  CATEGORY_CREATE_FAILED_ERROR: 'הוספת הקטגוריה נכשלה, אנא נסו מאוחר יותר',
  DELETE_CATEGORY: 'מחיקת קטגוריה',
  ARE_YOU_SURE: 'האם ברצונך למחוק?',
  CATEGORY_UPDATED_SUCCESSFULLY: 'עדכון הקטגוריה נשמר בהצלחה!',
  CATEGORY_UPDATED_ERROR: 'שגיאה בעדכון הקטגוריה, בבקשה נסו מאוחר יותר',
  DELETE_CATEGORY_CONFIRMATION:
    'האם ברצונך למחוק את הקטגוריה זו? זה לא יכול להיבטל.',
  DELETE_CATEGORY_SUCCESS: 'קטגוריה נמחקה בהצלחה!',
  DELETE_CATEGORY_ERROR: 'שגיאה במחיקת הקטגוריה, אנא נסו מאוחר יותר',
  EXPENSES_HISTORY: 'היסטוריית ההוצאות',
  DO_YOU_WANT_TO_DELETE: 'האם ברצונך למחוק?',
  NO_MISTAKE: 'לא, טעות',
  YES_PLEASE_DELETE: 'כן, מחק בבקשה',
  EDIT_EXPENSE: 'עריכת הוצאה',
  CANCEL: 'ביטול',
  EDIT: 'עריכה',
  ERROR_IN_LOADING_EXPENSES: 'שגיאה טעינת ההוצאות, בבקשה נסו מאוחר יותר',
  ERROR_IN_LOADING_CATEGORIES: 'שגיאה בטעינת הקטגוריות, בבקשה נסו מאוחר יותר',
  HELLO_USER: '👋 היי {{name}},',
  MONTH_EXPENSES_TEXT: 'החודש הוצאת',
  FROM: 'מתוך',
  EXPENSE_AMOUNT_PLACEHOLDER: 'סכום ההוצאה',
  EXPENSE_AMOUNT_REQUIRED: 'סכום חובה',
  EXPENSE_AMOUNT_REQUIRED_GREATER_THAN_ZERO: 'הסכום חייב להיות גדול מאפס',
  CATEGORY_MAX_AMOUNT_REQUIRED_ERROR: 'תקציב חייב להיות מספר תקין וחיובי',
  CATEGORY_ALREADY_EXISTS_ERROR: 'קיימת קטרוגיה בשם זה, אנא בחרו שם אחר',
  DELETE: 'מחיקה',
  DELETE_EXPENSE: 'מחיקת הוצאה',
  ON: 'על',
  ON_DATE: 'בתאריך',
  PAYMENT_PERFORMED_ON: 'העסקה בוצעה ב',
  PAYMENT_IN: 'הוצאה של',
  SAVE: 'שמירה',
  CHANGE_CATEGORY: 'שינוי קטגוריה',
  AMOUNT: 'סכום',
  NOTE: 'הערה',
  SELECT_PAYMENT_METHOD: 'בחירת אמצעי תשלום',
  EXPENSE_UPDATED_SUCCESSFULLY: 'עדכון ההוצאה נשמר בהצלחה',
  ERROR_IN_UPDATING_EXPENSE: 'שגיאה בעדכון ההוצאה, בבקשה נסו מאוחר יותר',
  SAVED: 'נשמר!',
  TRY_AGAIN_LATER: 'נסו שוב בעוד כמה דקות',
  GENERIC_ERROR: 'שגיאה כללית, בבקשה נסו מאוחר יותר',
  ALL_CATEGORIES: 'כל הקטגוריות',
  SUB_CATEGORIES: 'תתי קטגוריות',
  NO_SUB_CATEGORIES: 'אין תתי קטגוריות',
  HOW_MUCH_I_SPENT_THIS_MONTH: 'כמה הוצאתי החודש על {{categoryName}}?',
  TRACKING_EXPENSES: 'מעקב הוצאות חודשי',
  MONTH_BALANCE_TEXT: 'מאזן חודשי',
  OVER_BUDGET: 'חריגה!',
  BE_CAREFUL: 'הגעת למכסה החודש',
  YOU_ARE_IN_GOOD_STATE: 'מצב מעולה',
  SPENT: 'הוצאתי',
  PAY_ATTENTION: 'שים לב! יש לעקוב',
  SEARCH_PLACEHOLDER: 'חיפוש',
  SELECT_CATEGORY_FIRST: 'בחרי קודם קטגוריה',
  ADD_NOTE_PLACEHOLDER: 'תרצה/י להוסיף פירוט להוצאה?',
  CATEGORY_INACTIVE: '🚫 קטגוריה לא פעילה',
  SORT: 'מיון',
  FILTER: 'סינון',
  FILTER_ACTIVE: 'סינון: פעיל',
  NAME: 'שם',
  BUDGET: 'תקציב',
  SORT_ASC: 'סדר עולה',
  SORT_DESC: 'סדר יורד',
  // Login
  LOGIN_TITLE: 'שלום,',
  LOGIN_SUBTITLE: 'טוב לראות אותך שוב!',
  LOGIN_EMAIL: 'אימייל',
  LOGIN_EMAIL_PLACEHOLDER: 'דוגמה@example.com',
  LOGIN_EMAIL_REQUIRED: 'שדה אימייל חובה',
  LOGIN_EMAIL_INVALID: 'נא להזין אימייל תקין',
  LOGIN_PASSWORD: 'סיסמה',
  LOGIN_PASSWORD_PLACEHOLDER: 'הכנס/י סיסמה',
  LOGIN_PASSWORD_REQUIRED: 'שדה סיסמה חובה',
  LOGIN_SUBMIT: 'התחבר/י',
  LOGIN_MOVE_TO_REGISTER: 'אין לך חשבון? ',
  LOGIN_REGISTER_LINK: 'להרשמה יש ללחוץ כאן',
  // Register
  REGISTER_TITLE: 'הרשמה',
  REGISTER_SUBTITLE: 'יצירת חשבון חדש',
  REGISTER_NAME: 'שם מלא',
  REGISTER_NAME_PLACEHOLDER: 'הכנס/י את שמך',
  REGISTER_NAME_REQUIRED: 'שדה שם חובה',
  REGISTER_EMAIL: 'אימייל',
  REGISTER_EMAIL_PLACEHOLDER: 'דוגמה@example.com',
  REGISTER_EMAIL_REQUIRED: 'שדה אימייל חובה',
  REGISTER_EMAIL_INVALID: 'נא להזין אימייל תקין',
  REGISTER_PASSWORD: 'סיסמה',
  REGISTER_PASSWORD_PLACEHOLDER: 'לפחות 6 תווים',
  REGISTER_PASSWORD_REQUIRED: 'שדה סיסמה חובה',
  REGISTER_PASSWORD_MIN: 'סיסמה לפחות 6 תווים',
  REGISTER_CONFIRM_PASSWORD: 'אימות סיסמה',
  REGISTER_CONFIRM_PASSWORD_PLACEHOLDER: 'הכנס/י שוב את הסיסמה',
  REGISTER_CONFIRM_PASSWORD_REQUIRED: 'נא לאמת את הסיסמה',
  REGISTER_PASSWORDS_MISMATCH: 'הסיסמאות לא תואמות',
  REGISTER_SUBMIT: 'הרשמה',
  REGISTER_HAS_ACCOUNT: 'כבר יש לך חשבון?',
  REGISTER_LOGIN_LINK: 'התחברות',
  // Category Details
  CATEGORY_DETAILS: 'פרטי קטגוריה',
  // Top Bar
  SPENDO: 'Spendo',
  // Receipts
  RECEIPTS_DESCRIPTION: 'סרוק בבקשה את הקבלה הרצויה',
  // Redirect
  REDIRECT: 'מעבירים אותך...',
};
